# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/calendar.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CalendarWindow(object):
    def setupUi(self, CalendarWindow):
        CalendarWindow.setObjectName("CalendarWindow")
        CalendarWindow.resize(1062, 803)
        self.verticalLayout = QtWidgets.QVBoxLayout(CalendarWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BackButton = QtWidgets.QPushButton(CalendarWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BackButton.sizePolicy().hasHeightForWidth())
        self.BackButton.setSizePolicy(sizePolicy)
        self.BackButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/go-previous/go-previous.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BackButton.setIcon(icon)
        self.BackButton.setIconSize(QtCore.QSize(24, 24))
        self.BackButton.setFlat(True)
        self.BackButton.setObjectName("BackButton")
        self.horizontalLayout.addWidget(self.BackButton)
        self.bookingHistoryTitle = QtWidgets.QLabel(CalendarWindow)
        self.bookingHistoryTitle.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";")
        self.bookingHistoryTitle.setObjectName("bookingHistoryTitle")
        self.horizontalLayout.addWidget(self.bookingHistoryTitle)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.labelDateRange = QtWidgets.QLabel(CalendarWindow)
        self.labelDateRange.setObjectName("labelDateRange")
        self.verticalLayout.addWidget(self.labelDateRange)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.buttonPreviousWeek = QtWidgets.QPushButton(CalendarWindow)
        self.buttonPreviousWeek.setObjectName("buttonPreviousWeek")
        self.hboxlayout.addWidget(self.buttonPreviousWeek)
        self.buttonNextWeek = QtWidgets.QPushButton(CalendarWindow)
        self.buttonNextWeek.setObjectName("buttonNextWeek")
        self.hboxlayout.addWidget(self.buttonNextWeek)
        self.verticalLayout.addLayout(self.hboxlayout)
        self.tableTime = QtWidgets.QTableWidget(CalendarWindow)
        self.tableTime.setRowCount(24)
        self.tableTime.setColumnCount(7)
        self.tableTime.setObjectName("tableTime")
        self.verticalLayout.addWidget(self.tableTime)

        self.retranslateUi(CalendarWindow)
        QtCore.QMetaObject.connectSlotsByName(CalendarWindow)

    def retranslateUi(self, CalendarWindow):
        _translate = QtCore.QCoreApplication.translate
        self.bookingHistoryTitle.setText(_translate("CalendarWindow", "История бронирования"))
        self.labelDateRange.setText(_translate("CalendarWindow", "TextLabel"))
        self.buttonPreviousWeek.setText(_translate("CalendarWindow", "<"))
        self.buttonNextWeek.setText(_translate("CalendarWindow", ">"))
import resources_rc
