# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/Calendar.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CalendarApp(object):
    def setupUi(self, CalendarWindow):
        CalendarWindow.setObjectName("CalendarWindow")
        self.verticalLayout = QtWidgets.QVBoxLayout(CalendarWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelDateRange = QtWidgets.QLabel(CalendarWindow)
        self.labelDateRange.setObjectName("labelDateRange")
        self.verticalLayout.addWidget(self.labelDateRange)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.buttonPreviousWeek = QtWidgets.QPushButton(CalendarWindow)
        self.buttonPreviousWeek.setObjectName("buttonPreviousWeek")
        self.hboxlayout.addWidget(self.buttonPreviousWeek)
        self.buttonNextWeek = QtWidgets.QPushButton(CalendarWindow)
        self.buttonNextWeek.setObjectName("buttonNextWeek")
        self.hboxlayout.addWidget(self.buttonNextWeek)
        self.verticalLayout.addLayout(self.hboxlayout)
        self.tableWidget = QtWidgets.QTableWidget(CalendarWindow)
        self.tableWidget.setRowCount(24)
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setObjectName("tableWidget")
        self.verticalLayout.addWidget(self.tableWidget)

        self.retranslateUi(CalendarWindow)
        QtCore.QMetaObject.connectSlotsByName(CalendarWindow)

    def retranslateUi(self, CalendarWindow):
        _translate = QtCore.QCoreApplication.translate
        self.labelDateRange.setText(_translate("CalendarApp", "Дата"))
        self.buttonPreviousWeek.setText(_translate("CalendarApp", "<"))
        self.buttonNextWeek.setText(_translate("CalendarApp", ">"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CalendarWindow = QtWidgets.QWidget()
    ui = Ui_CalendarApp()
    ui.setupUi(CalendarWindow)
    CalendarWindow.show()
    sys.exit(app.exec_())
