# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/recordeditor.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RecordEditor(object):
    def setupUi(self, RecordEditor):
        RecordEditor.setObjectName("RecordEditor")
        RecordEditor.resize(640, 480)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(RecordEditor)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(RecordEditor)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 620, 419))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Form = QtWidgets.QFormLayout()
        self.Form.setObjectName("Form")
        self.verticalLayout_3.addLayout(self.Form)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.SaveButton = QtWidgets.QPushButton(RecordEditor)
        self.SaveButton.setObjectName("SaveButton")
        self.horizontalLayout_2.addWidget(self.SaveButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 85)
        self.verticalLayout.setStretch(1, 7)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(RecordEditor)
        QtCore.QMetaObject.connectSlotsByName(RecordEditor)

    def retranslateUi(self, RecordEditor):
        _translate = QtCore.QCoreApplication.translate
        RecordEditor.setWindowTitle(_translate("RecordEditor", "Form"))
        self.SaveButton.setText(_translate("RecordEditor", "Сохранить"))
