# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/relationtablechooser.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RelationTableView(object):
    def setupUi(self, RelationTableView):
        RelationTableView.setObjectName("RelationTableView")
        RelationTableView.resize(400, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(RelationTableView)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(RelationTableView)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 380, 233))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Table = QtWidgets.QTableView(self.scrollAreaWidgetContents_2)
        self.Table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.Table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.Table.setObjectName("Table")
        self.Table.horizontalHeader().setStretchLastSection(True)
        self.Table.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_3.addWidget(self.Table)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.ChooseButton = QtWidgets.QPushButton(RelationTableView)
        self.ChooseButton.setObjectName("ChooseButton")
        self.horizontalLayout.addWidget(self.ChooseButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 85)
        self.verticalLayout.setStretch(1, 15)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(RelationTableView)
        QtCore.QMetaObject.connectSlotsByName(RelationTableView)

    def retranslateUi(self, RelationTableView):
        _translate = QtCore.QCoreApplication.translate
        RelationTableView.setWindowTitle(_translate("RelationTableView", "Form"))
        self.ChooseButton.setText(_translate("RelationTableView", "Выбрать"))
